//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDiskLast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        public int Id { get; set; }
        public Nullable<int> EXPENSE_ACCOUNT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TAX_PERCENT { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<int> expense_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> comapny_id { get; set; }
    
        public virtual EXPENSE EXPENSE { get; set; }
        public virtual AccountTable AccountTable { get; set; }
    }
}
