//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDiskLast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadAccountTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeadAccountTable()
        {
            this.AccountTables = new HashSet<AccountTable>();
        }
    
        public int HeadAccountId { get; set; }
        public string HeadAccountTitle { get; set; }
        public string HeadAccountDescription { get; set; }
        public Nullable<int> FK_ControlAccountID { get; set; }
        public Nullable<int> FK_CompanyId { get; set; }
        public Nullable<int> AddedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTable> AccountTables { get; set; }
        public virtual ComapnyInfo ComapnyInfo { get; set; }
        public virtual ControlAccountTable ControlAccountTable { get; set; }
    }
}
