//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDiskLast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTermTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentTermTable()
        {
            this.AccountTransictionTables = new HashSet<AccountTransictionTable>();
        }
    
        public int PayementTremId { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<int> FK_CompanyID { get; set; }
        public Nullable<int> AddebBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransictionTable> AccountTransictionTables { get; set; }
    }
}
